name: Publish
on:
  push:
    branches:
      - develop
      - main

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Build project with Java ${{ matrix.java }} and publish builds to GitHub Maven Repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Get version
        id: release-version
        run: |
          export VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$VERSION"

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}