name: Verify
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Build project with Java ${{ matrix.java }} and Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          mvn verify
